global:
  namespace: mochat
  createNamespace: false
  imageRegistry: localhost/mochat
  projectId: mochat-local
  environment: local

externalDependencies:
  redisUri: redis://host.docker.internal:6379
  postgresUrl: jdbc:postgresql://host.docker.internal:5432/mochat
  rocketmqNameServer: host.docker.internal:9876
  secret:
    create: true
    postgresUsername: mochat
    postgresPassword: mochat

accessGatewayTls:
  create: true
  certificate: ""
  privateKey: ""

livekit:
  createSecret: true
  url: ""
  apiKey: ""
  apiSecret: ""

apiService:
  service:
    type: NodePort
  ports:
    nodePort: 30080

callService:
  service:
    type: NodePort
  ports:
    nodePort: 32090
