mochat:
  redis:
    uri: redis://127.0.0.1:6379
  rocketmq:
    name-server: 127.0.0.1:9876
  runtime:
    gateway:
      identity-mode: CONFIGURED
      identity-value: gateway-a
      discovery-mode: STATIC_MAP
  message-service:
    route:
      gateway-targets:
        gateway-a: 127.0.0.1:19093

grpc:
  channels:
    api-service:
      address: 127.0.0.1:19091
      plaintext: true
