apiVersion: v1
kind: Secret
metadata:
  name: mochat-external-dependency-secrets
  namespace: mochat
type: Opaque
stringData:
  MOCHAT_POSTGRES_USERNAME: ""
  MOCHAT_POSTGRES_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: access-gateway-tls
  namespace: mochat
type: kubernetes.io/tls
stringData:
  tls.crt: ""
  tls.key: ""
