name: mo-chat

services:
  postgres:
    image: docker.1ms.run/postgres:17
    container_name: mo-chat-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_USER=mochat
      - POSTGRES_PASSWORD=mochat
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: docker.1ms.run/redis:7.2
    container_name: mo-chat-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  rocketmq-namesrv:
    image: docker.1ms.run/apache/rocketmq:5.3.2
    container_name: mo-chat-rocketmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"

  rocketmq-broker:
    image: docker.1ms.run/apache/rocketmq:5.3.2
    container_name: mo-chat-rocketmq-broker
    command: sh mqbroker -n rocketmq-namesrv:9876
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    depends_on:
      - rocketmq-namesrv

  rustfs:
    image: docker.1ms.run/rustfs/rustfs:latest
    container_name: mo-chat-rustfs
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=:9001
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  rustfs-data:
  rustfs-logs:
