{{- if .Values.externalDependencies.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDependencies.secret.name }}
  namespace: {{ include "mochat.namespace" . }}
  labels:
    {{- include "mochat.labels" . | nindent 4 }}
type: Opaque
stringData:
  MOCHAT_POSTGRES_USERNAME: {{ .Values.externalDependencies.secret.postgresUsername | quote }}
  MOCHAT_POSTGRES_PASSWORD: {{ .Values.externalDependencies.secret.postgresPassword | quote }}
{{- end }}
