apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mochat.serviceAccountName" . }}
  namespace: {{ include "mochat.namespace" . }}
  labels:
    {{- include "mochat.labels" . | nindent 4 }}
