-- MoChat Phase 1 baseline schema (PostgreSQL)
-- Notes:
-- - All primary keys are generated by application Snowflake ID generator (BIGINT).
-- - This file is a design-time baseline; migrations (Flyway/Liquibase) may split it later.

CREATE TABLE IF NOT EXISTS users (
  id           BIGINT PRIMARY KEY,
  username     TEXT   NOT NULL UNIQUE,
  public_key   BYTEA  NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_public_key_len_chk CHECK (octet_length(public_key) = 32)
);

-- Friend relation is modeled as an unordered pair (uid_1 < uid_2).
-- status:
--   ok      -> normal friendship
--   blocked -> both sides cannot message each other; blocked_by indicates who initiated
CREATE TABLE IF NOT EXISTS user_friendships (
  id           BIGINT PRIMARY KEY,
  uid_1        BIGINT NOT NULL,
  uid_2        BIGINT NOT NULL,
  status       TEXT   NOT NULL,
  blocked_by   SMALLINT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_friendships_uid_order_chk CHECK (uid_1 < uid_2),
  CONSTRAINT user_friendships_status_chk CHECK (status IN ('ok', 'blocked')),
  CONSTRAINT user_friendships_blocked_by_chk CHECK (
    (status = 'ok' AND blocked_by IS NULL) OR
    (status = 'blocked' AND blocked_by IN (0, 1))
  ),
  CONSTRAINT user_friendships_pair_uniq UNIQUE (uid_1, uid_2)
);

CREATE INDEX IF NOT EXISTS user_friendships_uid1_idx ON user_friendships (uid_1);
CREATE INDEX IF NOT EXISTS user_friendships_uid2_idx ON user_friendships (uid_2);
CREATE INDEX IF NOT EXISTS user_friendships_status_idx ON user_friendships (status);

-- Friend request is stored even though server does not validate sign.
-- status: pending / accepted / rejected / cancelled
CREATE TABLE IF NOT EXISTS friend_requests (
  id           BIGINT PRIMARY KEY,
  from_uid     BIGINT NOT NULL,
  to_uid       BIGINT NOT NULL,
  sign         TEXT   NOT NULL,
  status       TEXT   NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  handled_at   TIMESTAMPTZ,
  CONSTRAINT friend_requests_status_chk CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS friend_requests_to_status_created_idx ON friend_requests (to_uid, status, created_at);
CREATE INDEX IF NOT EXISTS friend_requests_from_status_created_idx ON friend_requests (from_uid, status, created_at);

-- Optional: prevent duplicate pending requests for same pair.
CREATE UNIQUE INDEX IF NOT EXISTS friend_requests_pending_pair_uniq
  ON friend_requests (from_uid, to_uid)
  WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS groups (
  id           BIGINT PRIMARY KEY,
  owner_uid    BIGINT NOT NULL,
  name         TEXT   NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS groups_owner_idx ON groups (owner_uid);

-- Group membership status: active / left / kicked
-- role: owner / member (can be extended later)
CREATE TABLE IF NOT EXISTS group_memberships (
  id           BIGINT PRIMARY KEY,
  group_id     BIGINT NOT NULL,
  user_id      BIGINT NOT NULL,
  role         TEXT   NOT NULL,
  status       TEXT   NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT group_memberships_role_chk CHECK (role IN ('owner', 'member')),
  CONSTRAINT group_memberships_status_chk CHECK (status IN ('active', 'left', 'kicked')),
  CONSTRAINT group_memberships_pair_uniq UNIQUE (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS group_memberships_user_idx ON group_memberships (user_id, status);
CREATE INDEX IF NOT EXISTS group_memberships_group_idx ON group_memberships (group_id, status);

-- Group join requests are handled by the group owner.
-- status: pending / accepted / rejected / cancelled
CREATE TABLE IF NOT EXISTS group_join_requests (
  id           BIGINT PRIMARY KEY,
  group_id     BIGINT NOT NULL,
  from_uid     BIGINT NOT NULL,
  sign         TEXT   NOT NULL,
  status       TEXT   NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  handled_by   BIGINT,
  handled_at   TIMESTAMPTZ,
  CONSTRAINT group_join_requests_status_chk CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS group_join_requests_group_status_created_idx ON group_join_requests (group_id, status, created_at);
CREATE INDEX IF NOT EXISTS group_join_requests_from_status_created_idx ON group_join_requests (from_uid, status, created_at);

-- Messages:
-- - msg_id: server Snowflake ID (global unique)
-- - client_msg_id: client-generated ID used for idempotency per sender
-- - payload_base64: base64 encoding of protobuf message body (for HTTP history retrieval)
-- - For private chat, conversation is addressed by (peer_uid_low, peer_uid_high).
CREATE TABLE IF NOT EXISTS messages (
  msg_id        BIGINT PRIMARY KEY,
  client_msg_id BIGINT NOT NULL,
  kind          TEXT   NOT NULL,
  sender_uid    BIGINT NOT NULL,
  peer_uid_low  BIGINT,
  peer_uid_high BIGINT,
  group_id      BIGINT,
  server_ts_ms  BIGINT NOT NULL,
  payload_base64 TEXT NOT NULL,
  CONSTRAINT messages_kind_chk CHECK (kind IN ('private', 'group')),
  CONSTRAINT messages_routing_fields_chk CHECK (
    (kind = 'private'
      AND group_id IS NULL
      AND peer_uid_low IS NOT NULL
      AND peer_uid_high IS NOT NULL
    ) OR
    (kind = 'group'
      AND group_id IS NOT NULL
      AND peer_uid_low IS NULL
      AND peer_uid_high IS NULL
    )
  )
);

-- Idempotency uniqueness for persistence/debugging.
CREATE UNIQUE INDEX IF NOT EXISTS messages_sender_client_msg_uniq ON messages (sender_uid, client_msg_id);

-- Efficient history pagination:
CREATE INDEX IF NOT EXISTS messages_private_pair_msg_id_idx ON messages (peer_uid_low, peer_uid_high, msg_id DESC) WHERE kind = 'private';
CREATE INDEX IF NOT EXISTS messages_group_msg_id_idx ON messages (group_id, msg_id DESC) WHERE kind = 'group';
