apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mo-chat-observability.mochatSecretName" . }}
  labels:
    {{- include "mo-chat-observability.mochatLabels" . | nindent 4 }}
type: Opaque
stringData:
  MOCHAT_POSTGRES_PASSWORD: {{ .Values.mochat.env.postgresPassword | quote }}
  RUSTFS_SECRET_KEY: {{ .Values.mochat.env.rustfsSecretKey | quote }}
