micronaut:
  application:
    name: api-service
  server:
    host: ${MOCHAT_API_SERVICE_HTTP_HOST:0.0.0.0}
    port: ${MOCHAT_API_SERVICE_HTTP_PORT:8080}

mochat:
  api-service:
    http:
      host: ${MOCHAT_API_SERVICE_HTTP_HOST:0.0.0.0}
      port: ${MOCHAT_API_SERVICE_HTTP_PORT:8080}
    grpc:
      port: ${MOCHAT_API_SERVICE_GRPC_PORT:19091}
    dependencies:
      redis-enabled: ${MOCHAT_API_SERVICE_REDIS_ENABLED:true}
      postgres-enabled: ${MOCHAT_API_SERVICE_POSTGRES_ENABLED:true}

grpc:
  server:
    port: ${MOCHAT_API_SERVICE_GRPC_PORT:19091}
